[project]
name = "img2txt-comfyui-nodes"
description = "Nodes:img2txt BLIP SalesForce Large"
version = "1.0.0"
license = "LICENSE"
dependencies = ["transformers>=4.35.3", "bitsandbytes>=0.43.0"]

[project.urls]
Repository = "https://github.com/christian-byrne/img2txt-comfyui-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "img2txt-comfyui-nodes"
Icon = ""
